name: Build and Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Release
    runs-on: ubuntu-latest

    env:
      BLOCKCORE: "blockcore"
      COINVAULT: "coinvault"
      SMARTCITYPLATFORM: "smartcityplatform"

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Variables
        run: |
          echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
        shell: bash

      - name: Package Name
        run: |
          echo RELEASE_NAME_BLOCKCORE=${{ env.BLOCKCORE }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
          echo RELEASE_NAME_COINVAULT=${{ env.COINVAULT }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
          echo RELEASE_NAME_SMARTCITYPLATFORM=${{ env.SMARTCITYPLATFORM }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
        shell: bash

      - name: Setup
        run: npm ci

      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
        continue-on-error: true

      # - name: Build
      #   run: npm run all

      - name: Package Blockcore
        run: |
          npm run build:production
          cd dist/extension
          zip -r ../../${{env.RELEASE_NAME_BLOCKCORE}} "./"
          cd ../../
          rm -rf  dist/extension

      - name: Package CoinVault
        run: |
          npm run build:coinvault
          cd dist/extension
          zip -r ../../${{env.RELEASE_NAME_COINVAULT}} "./"
          cd ../../
          rm -rf dist/extension

      - name: Package SmartCityPlatform
        run: |
          npm run build:smartcityplatform
          cd dist/extension
          zip -r ../../${{env.RELEASE_NAME_SMARTCITYPLATFORM}} "./"
          cd ../../
          rm -rf  dist/extension

      - name: Upload Blockcore
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.BLOCKCORE}}-preview-${{env.VERSION}}
          path: "${{env.RELEASE_NAME_BLOCKCORE}}"

      - name: Upload CoinVault
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.COINVAULT}}-preview-${{env.VERSION}}
          path: "${{env.RELEASE_NAME_COINVAULT}}"

      - name: Upload SmartCityPlatform
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.SMARTCITYPLATFORM}}-preview-${{env.VERSION}}
          path: "${{env.RELEASE_NAME_SMARTCITYPLATFORM}}"

      - name: Create/Update Draft Release
        uses: sondreb/action-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "${{env.RELEASE_NAME_BLOCKCORE}};${{env.RELEASE_NAME_COINVAULT}};${{env.RELEASE_NAME_SMARTCITYPLATFORM}}"
          draft: true
          prerelease: false
          name: "Blockcore Wallet (${{env.VERSION}})"
          tag: ${{env.VERSION}}
